apiVersion: batch/v1
kind: Job
metadata:
  name: s2456316-open-x-embodiment-train-run
spec:
  parallelism: 1
  template:
    metadata:
      name: s2456316-open-x-embodiment-train-run
      labels:
        app: s2456316-open-x-embodiment-train-run
    spec:
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB
      volumes:
        - name: s2456316-open-x-embodiment
          persistentVolumeClaim:
            claimName: s2456316-open-x-embodiment
        - name: robot-baseline-code
          emptyDir: {}
        - name: s2456316-git-ssh
          secret:
            secretName: s2456316-git-ssh
            defaultMode: 0400
      imagePullSecrets:
        - name: s2456316-ghcr-secret
      restartPolicy: OnFailure
      containers:
        - name: s2456316-open-x-embodiment-train-run
          image: ghcr.io/peterdavidfagan/open-x-embodiment-train-run:latest
          workingDir: /app/code_refresh/robot_learning_baselines.git/robot_learning_baselines
          # TODO: add activation on python env 
          args: ["python", "/app/code_refresh/robot_learning_baselines.git/robot_learning_baselines/train_meta_concept_learner.py", "+move_puzzle=container_concept_learner_meta"]
          env:
          volumeMounts:
            - name: robot-baseline-code
              mountPath: "/app/code_refresh"
            - name: s2456316-open-x-embodiment
              mountPath: "/app/data"
          resources:
            limits:
              nvidia.com/gpu: 1
      initContainers:
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.0.0
          args:
            - --repo=git@github.com:peterdavidfagan/robot_learning_baselines.git
            - --root=/app
            - --ssh=true
            - --ssh-known-hosts=false
            - --one-time=true
          volumeMounts:
            - name: robot-baseline-code
              mountPath: "/app"
            - name: s2456316-git-ssh
              mountPath: "/etc/git-secret"
              readOnly: true
          securityContext:
            runAsUser: 65533
      securityContext:
        fsGroup: 65533
