project:
  base_path: /home/peter/Code/research_projects/robot_learning_baselines

wandb:
  use: True
  project: "robot_learning_baselines"
  entity: "ipab-rad"
  experiment_name: octo-continuous
  tags: ["debugging octo pipeline"]
  notes: "Debugging octo training pipeline."
  resume: False

  dataset_visualization:
    columns:
      task/language_instruction: "text"
      observation/image_primary: "image"

  model_gradients:
    columns:
      param_name: null
      mean: null
      variance: null
      max_val: null
      min_val: null

debug_run: True
defaults:
  - architecture/multi_modal_transformer: octo-categorical
  - dataset: debug-open-x-embodiment
  - evaluation: octo-base
  - training: octo-base
