project:
  base_path: /home/peter/Code/research_projects/robot_learning_baselines

wandb:
  use: True
  project: "robot_learning_baselines"
  entity: "ipab-rad"
  experiment_name: octo-perf-bench
  tags: ["Performance Benchmark"]
  notes: "Benchmark OCTO performance."
  resume: False


defaults:
  - architecture/multi_modal_transformer: octo-base 
  - dataset: debug-open-x-embodiment
  - evaluation: octo-base
  - training: octo-base
