project:
  base_path: /home/peter/Code/research_projects/robot_learning_baselines

wandb:
  use: True
  experiment_name: octo-base
  tags: ["debugging octo pipeline"]
  notes: "Debugging octo training pipeline."

defaults:
  - architecture/multi_modal_transformer: octo-base 
  - dataset: debug-open-x-embodiment # open-x-embodiment
  - evaluation: octo-base
  - training: octo-base
