project:
  base_path: /home/peter/Code/research_projects/robot_learning_baselines

wandb:
  use: True
  project: "robot_learning_baselines"
  entity: "ipab-rad"
  experiment_name: transporter-debug
  tags: ["debugging transporter pipeline"]
  notes: "Debugging transporter training pipeline."
  resume: False

  dataset_visualization:
    columns:
      rgb: "image"
      depth: "image"
      rgb_crop: "image"
      depth_crop: "image"
      pick_target: "image"
      place_target: "image"

debug_run: True
defaults:
  - architecture/transporter: transporter
  - dataset: debug-transporter
  - evaluation: transporter
  - training: transporter
