apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypoint-template
data:
  my-script.sh: |-
    #!/bin/bash

    # activate built poetry env
    cd /app
    source $(poetry env info --path)/bin/activate

    # login to wandb
    wandb login

    # execute training command
    cd /app/code_refresh/<repo>.git/repo/src/
    exec "$@"
