version: "3"
services:
  jax:
    image: ghcr.io/peterdavidfagan/transporter:latest
    build:
      context: ../../
      dockerfile: .docker/transporter/Dockerfile.jax
    volumes:
        #- /home/peter/tensorflow_datasets:/app/tensorflow_datasets
    environment:
    network_mode: host
    privileged: true
    cap_add:
      - SYS_NICE
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    command: python /app/
