apiVersion: v1
kind: Pod
metadata:
  name: s2456316-open-x-embodiment-data-debug
  labels:
    eidf/user: s2456316-infk8s
spec:
  volumes:
    - name: s2456316-open-x-embodiment
      persistentVolumeClaim:
        claimName: s2456316-open-x-embodiment
    - name: robot-baseline-code
      emptyDir: {}
    - name: s2456316-git-ssh
      secret:
        secretName: s2456316-git-ssh
        defaultMode: 0400
  imagePullSecrets:
    - name: s2456316-ghcr-secret
  restartPolicy: Never
  containers:
    - name: robot-learning-baselines-train-container
      image: ghcr.io/peterdavidfagan/robot_learning_baselines_train:latest
      resources:
        limits:
          cpu: 12
          memory: 32Gi
      command: ["/bin/bash"]
      args: ["-c", "sleep 3600"]
      volumeMounts:
        - name: robot-baseline-code
          mountPath: "/app/code_refresh"
        - name: s2456316-open-x-embodiment
          mountPath: "/app/data"
  initContainers:
      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v4.0.0
        resources:
          limits:
            cpu: 12
            memory: 32Gi
        args:
          - --repo=git@github.com:peterdavidfagan/robot_learning_baselines.git
          - --root=/app
          - --ssh=true
          - --ssh-known-hosts=false
          - --one-time=true
        volumeMounts:
          - name: robot-baseline-code
            mountPath: "/app"
          - name: s2456316-git-ssh
            mountPath: "/etc/git-secret"
            readOnly: true
        securityContext:
          runAsUser: 65533
  securityContext:
    fsGroup: 65533
