apiVersion: v1
kind: Pod
metadata:
  name: s2456316-open-x-embodiment-data-transfer
spec:
  volumes:
    - name: s2456316-open-x-embodiment
      persistentVolumeClaim:
        claimName: s2456316-open-x-embodiment
  imagePullSecrets:
    - name: s2456316-ghcr-secret
  restartPolicy: Never
  containers:
    - name: s2456316-open-x-embodiment-data-transfer
      image: ghcr.io/peterdavidfagan/open_x_embodiment_data_transfer
      resources:
        limits:
          cpu: 12
          memory: 32Gi
      command: ["/bin/bash"]
      args: ["-c", "source .venv/bin/activate && python /app/code_refresh/robot_learning_baselines.git/robot_learning_baselines/data_loaders/open-x-embodiment.py --data_transfer=True --data_dir=/app/data/open-x-embodiment"]
      volumeMounts:
        - name: robot-baseline-code
          mountPath: "/app/code_refresh"
        - name: s2456316-open-x-embodiment
          mountPath: "/app/data"
  initContainers:
      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v4.0.0
        args:
          - --repo=git@github.com:peterdavidfagan/robot_learning_baselines.git
          - --root=/app
          - --ssh=true
          - --ssh-known-hosts=false
          - --one-time=true
        volumeMounts:
          - name: robot-baseline-code
            mountPath: "/app"
          - name: s2456316-git-ssh
            mountPath: "/etc/git-secret"
            readOnly: true
        securityContext:
          runAsUser: 65533
    securityContext:
      fsGroup: 65533

