action_space_dim: 7
heads:
  - categorical_action_head:
      _target_: multi_modal_transformers.action_heads.categorical.CategoricalActionHead
      dense:
        _target_: flax.linen.Dense
        features: ${config.architecture.multi_modal_transformer.action_heads.action_space_dim}
        kernel_init:
          _target_: flax.linen.initializers.he_normal
        use_bias: true
        bias_init:
          _target_: flax.linen.initializers.normal      

