num_epochs: 100
batch_size: 8

# checkpoint manager
checkpoint_dir: ${project.base_path}/.checkpoints/${wandb.experiment_name}/transporter_place
max_checkpoints: 2
save_interval: 50

optimizer:
  _target_: optax.adam
  learning_rate: 1e-4
